_wandb:
    value:
        cli_version: 0.21.0
        e:
            z9xgdukl4uebkxcwebs5zwimxbszj1lq:
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 48
                cpu_count_logical: 48
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "42928701440"
                        used: "14722560000"
                email: liamlaidlaw@boisestate.edu
                executable: /bsuhome/liamlaidlaw/miniforge3/envs/FederatedResnet/bin/python
                git:
                    commit: e25b0b5e341c04ae15dfdc320efd88b439039008
                    remote: https://github.com/lla1dlaw/ddp_resnet.git
                gpu: Tesla V100-PCIE-16GB
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Volta
                      cudaCores: 5120
                      memoryTotal: "17179869184"
                      name: Tesla V100-PCIE-16GB
                      uuid: GPU-1f09fdae-477d-19e2-f484-dd9571f4219d
                    - architecture: Volta
                      cudaCores: 5120
                      memoryTotal: "17179869184"
                      name: Tesla V100-PCIE-16GB
                      uuid: GPU-e0ed0109-e4a7-9b9a-2c85-e1dd2f6fdac9
                host: gpu101
                memory:
                    total: "404158652416"
                os: Linux-3.10.0-1160.119.1.el7.x86_64-x86_64-with-glibc2.17
                program: /bsuhome/liamlaidlaw/ddp_resnet/train.py
                python: CPython 3.11.13
                root: /bsuhome/liamlaidlaw/ddp_resnet
                slurm:
                    cluster_name: slurm
                    conf: /cm/shared/apps/slurm/var/etc/slurm/slurm.conf
                    cpus_on_node: "24"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: liamlaidlaw
                    job_cpus_per_node: "24"
                    job_end_time: "1752815027"
                    job_gid: "695487"
                    job_gpus: "0"
                    job_id: "2059347"
                    job_name: DEVSESSION
                    job_nodelist: gpu101
                    job_num_nodes: "1"
                    job_partition: gpu-v100
                    job_qos: devsession
                    job_start_time: "1752800627"
                    job_uid: "695487"
                    job_user: liamlaidlaw
                    jobid: "2059347"
                    launch_node_ipaddr: 172.18.0.14
                    localid: "0"
                    mpi_type: none
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: gpu101
                    nprocs: "24"
                    ntasks: "24"
                    prio_process: "0"
                    procid: "0"
                    pty_port: "40675"
                    pty_win_col: "175"
                    pty_win_row: "47"
                    srun_comm_host: 172.18.0.14
                    srun_comm_port: "44393"
                    step_id: "4294967290"
                    step_launcher_port: "44393"
                    step_nodelist: gpu101
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_tasks_per_node: "1"
                    stepid: "4294967290"
                    submit_dir: /bsuhome/liamlaidlaw
                    submit_host: borah-login
                    task_pid: "125711"
                    tasks_per_node: "24"
                    topology_addr: gpu101
                    topology_addr_pattern: node
                    working_cluster: slurm:borah-hn001:6817:9984:109
                startedAt: "2025-07-18T01:52:42.368739Z"
                writerId: z9xgdukl4uebkxcwebs5zwimxbszj1lq
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 16
            "4": 3.11.13
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
architecture:
    value: ResNet
dataset:
    value: CIFAR10
epochs:
    value: 5
