_wandb:
    value:
        cli_version: 0.21.0
        e:
            pycab32ysdr9k71w09u9hxp8a09u2tug:
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 48
                cpu_count_logical: 48
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "42928701440"
                        used: "14722568192"
                email: liamlaidlaw@boisestate.edu
                executable: /bsuhome/liamlaidlaw/miniforge3/envs/FederatedResnet/bin/python
                git:
                    commit: 4d608a0a1d41a88debf538e8f77f63aece35b28f
                    remote: https://github.com/lla1dlaw/ddp_resnet.git
                gpu: Tesla V100-PCIE-16GB
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Volta
                      cudaCores: 5120
                      memoryTotal: "17179869184"
                      name: Tesla V100-PCIE-16GB
                      uuid: GPU-653126a9-d6bd-44b7-f921-aacd16cdb7f2
                    - architecture: Volta
                      cudaCores: 5120
                      memoryTotal: "17179869184"
                      name: Tesla V100-PCIE-16GB
                      uuid: GPU-61b4d5a2-7747-1d27-4c5c-490a050c6c20
                host: gpu103
                memory:
                    total: "404158652416"
                os: Linux-3.10.0-1160.119.1.el7.x86_64-x86_64-with-glibc2.17
                program: /bsuhome/liamlaidlaw/ddp_resnet/train.py
                python: CPython 3.11.13
                root: /bsuhome/liamlaidlaw/ddp_resnet
                slurm:
                    cluster_name: slurm
                    conf: /cm/shared/apps/slurm/var/etc/slurm/slurm.conf
                    cpus_on_node: "24"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: liamlaidlaw
                    job_cpus_per_node: "24"
                    job_end_time: "1752883031"
                    job_gid: "695487"
                    job_gpus: "0"
                    job_id: "2060269"
                    job_name: DEVSESSION
                    job_nodelist: gpu103
                    job_num_nodes: "1"
                    job_partition: gpu-v100
                    job_qos: devsession
                    job_start_time: "1752868631"
                    job_uid: "695487"
                    job_user: liamlaidlaw
                    jobid: "2060269"
                    launch_node_ipaddr: 172.18.0.14
                    localid: "0"
                    mpi_type: none
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: gpu103
                    nprocs: "24"
                    ntasks: "24"
                    prio_process: "0"
                    procid: "0"
                    pty_port: "40405"
                    pty_win_col: "235"
                    pty_win_row: "57"
                    srun_comm_host: 172.18.0.14
                    srun_comm_port: "33323"
                    step_id: "4294967290"
                    step_launcher_port: "33323"
                    step_nodelist: gpu103
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_tasks_per_node: "1"
                    stepid: "4294967290"
                    submit_dir: /bsuhome/liamlaidlaw
                    submit_host: borah-login
                    task_pid: "196779"
                    tasks_per_node: "24"
                    topology_addr: gpu103
                    topology_addr_pattern: node
                    working_cluster: slurm:borah-hn001:6817:9984:109
                startedAt: "2025-07-18T23:38:17.066944Z"
                writerId: pycab32ysdr9k71w09u9hxp8a09u2tug
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 16
            "4": 3.11.13
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
architecture:
    value: ResNet
dataset:
    value: CIFAR10
epochs:
    value: 5
